### PR TITLE
Fixes to CILogon / `openid_connect` Tests

### LINKED ISSUE #921: Address Flaky Tests Due to Overriding of `OmniAuth.config.mock_auth[:openid_connect]`
Please complete the following fields as applicable:

**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**
- `4.1.1+portage-4.2.2`

**Expected behaviour:**
- The tests defined in `spec/integration/openid_connect_sso_spec.rb` largely rely on `OmniAuth.config.mock_auth[:openid_connect]`, which is defined in `spec/spec_helper.rb`.
  - For example, `expect(identifiable.firstname).to eql('John')` relies  on `first_name: 'John',` defined in `spec/spec_helper.rb`.

**Actual behaviour:**
- The aforementioned tests sometimes fail. The following is an example of one such error:
```ruby
  3) Openid_connection SSO with correct credentials creates account from external credentials
     Failure/Error: expect(identifiable.firstname).to eql('John')
     
       expected: "John"
            got: "Test"
     
       (compared using eql?)
     # ./spec/integration/openid_connect_sso_spec.rb:35:in `block (3 levels) in <top (required)>'
     # /usr/share/rvm/gems/ruby-3.1.4@dmp/gems/webmock-3.23.1/lib/webmock/rspec.rb:39:in `block (2 levels) in <top (required)>'
```

**Diagnosis:**
- The flaky nature of these tests seem to be due to the overriding of `OmniAuth.config.mock_auth[:openid_connect]` within `spec/controllers/omniauth_callbacks_controller_spec.rb`:
```ruby
    # Mock OmniAuth data for OpenID Connect with necessary info
    OmniAuth.config.mock_auth[:openid_connect] = OmniAuth::AuthHash.new({
                                                                          provider: 'openid_connect',
                                                                          uid: '12345',
                                                                          info: {
                                                                            email: 'user@organization.ca',
                                                                            first_name: 'Test',
                                                                            last_name: 'User',
                                                                            name: 'Test User'
                                                                          }
                                                                        })

    # Assign the mocked authentication hash to the request environment
    @request.env['omniauth.auth'] = OmniAuth.config.mock_auth[:openid_connect]
```
The flaky nature of these tests seems to be related to the combination of the re-assignment to `OmniAuth.config.mock_auth[:openid_connect]` and the random order of that the RSpec tests are executed. That is, if `spec/integration/openid_connect_sso_spec.rb` is executed before `spec/controllers/omniauth_callbacks_controller_spec.rb`, then the tests pass. Otherwise, they fail.

### PR DESCRIPTION
**Pull request by aaronskiba**
Fixes #921

Changes proposed in this PR:
- Fix flaky tests due to overriding of `OmniAuth.config.mock_auth[:openid_connect]` [648d6d8](https://github.com/portagenetwork/roadmap/pull/922/commits/648d6d848832b31ddbca4fa7420070e4aaef219b)
  - Prior to this PR, whenever `OmniAuth.config.mock_auth[:openid_connect]` was being overridden in this file, the value was always subsequently assigned to `@request.env['omniauth.auth']`. These changes simply bypass `OmniAuth.config.mock_auth[:openid_connect]` and directly assign `OmniAuth::AuthHash.new(...)` to `@request.env['omniauth.auth']` instead.

- Update and re-enable openid_connect features tests [4fd0f55](https://github.com/portagenetwork/roadmap/pull/922/commits/4fd0f55d5a0faa73ab979aef7f58b709f84659c6)
  - config/secrets.yml
    - `Rails.application.secrets.omniauth_full_host` does not appear to be necessary in test mode. In fact, if a value exists for `ENV['OMNIAUTH_FULL_HOST']` (e.g. the value set for development) then it results in the tests failing (By default, `Capybara.server_port` is set to a random value, so hardcoding a secret isn't completely straightforward.)
  - spec/integration/openid_connect_sso_spec.rb
    - Here we are re-enabling the "links account from external credentails" test, which was failing due to the aforementioned issue with `config/secrets.yml`.
    - We are also adding `:js`, which if desired, makes it simpler to execute these tests in non-headless mode.

### CODE REVIEW

File: spec/integration/openid_connect_sso_spec.rb [hunk 1]
```diff
@@ -24,7 +24,7 @@
       Rails.application.env_config['omniauth.auth'] = OmniAuth.config.mock_auth[:openid_connect]
     end
 
-    it 'creates account from external credentials' do
+    it 'creates account from external credentials', :js do
```
Comment (lagoan) [inline spec/integration/openid_connect_sso_spec.rb:23]: These tests continue to be flaky

File: spec/integration/openid_connect_sso_spec.rb [hunk 2]
```diff
@@ -51,7 +51,7 @@
       expect(user.identifiers.count).to eql(0)
     end
 
-    xit 'links account from external credentails' do
+    it 'links account from external credentails', :js do
```
Comment (lagoan) [inline spec/integration/openid_connect_sso_spec.rb:50]: These tests continue to be flaky

File: spec/controllers/omniauth_callbacks_controller_spec.rb [hunk 3]
```diff
@@ -15,19 +15,17 @@
...
+    @request.env['omniauth.auth'] = OmniAuth::AuthHash.new({
+                                                             provider: 'openid_connect',
+                                                             uid: '12345',
+                                                             info: {
+                                                               email: 'user@organization.ca',
+                                                               first_name: 'Test',
+                                                               last_name: 'User',
+                                                               name: 'Test User'
+                                                             }
+                                                           })
```
Comment (lagoan) [inline spec/controllers/omniauth_callbacks_controller_spec.rb]: Its been a while since I worked on this but believe we dont need to define ``@request.env['omniauth.auth'] ``

**Review by lagoan — CHANGES_REQUESTED** [review]
There are a couple of fixes here that I think can be improved. I left comments on this PR and you can check this [branch](https://github.com/portagenetwork/roadmap/tree/omar/issues/921)  for reference on some ideas.

File: spec/controllers/omniauth_callbacks_controller_spec.rb (hunk 3 above)
Comment (aaronskiba) [reply spec/controllers/omniauth_callbacks_controller_spec.rb]: > Its been a while since I worked on this but believe we dont need to define `@request.env['omniauth.auth'] `

I'm thinking we might need it. The `def openid_connect` method (`app/controllers/users/omniauth_callbacks_controller.rb`) has `auth = request.env['omniauth.auth']`. The tests appear to be failing without it: https://github.com/portagenetwork/roadmap/actions/runs/11409377997/job/31749474766

Rather than using `@request.env['omniauth.auth'] = OmniAuth::AuthHash.new({...` here, maybe we could  use `Rails.application.env_config['omniauth.auth'] = OmniAuth.config.mock_auth[:openid_connect]` like we did in `spec/integration/openid_connect_sso_spec.rb`?

File: spec/integration/openid_connect_sso_spec.rb (hunk 2 above)
Comment (aaronskiba) [reply spec/integration/openid_connect_sso_spec.rb:50]: You are right, thanks for catching that.
`rspec ./spec/controllers/omniauth_callbacks_controller_spec.rb ./spec/integration --seed=10840` is at least one way to trigger failed tests.

File: spec/controllers/omniauth_callbacks_controller_spec.rb (hunk 3 above)
Comment (aaronskiba) [reply spec/controllers/omniauth_callbacks_controller_spec.rb]: Also, I was conflating `@request.env` with `Rails.application.env_config`. Maybe there is a conflict occurring between these two.

Comment (aaronskiba) [reply spec/controllers/omniauth_callbacks_controller_spec.rb]: I think the real issue was that the overriding of `User.from_omniauth` in `spec/controllers/omniauth_callbacks_controller_spec.rb` was persisting beyond that test file. I've addressed the issue here: https://github.com/portagenetwork/roadmap/pull/922/commits/8d2fd866ab6245e6311a6bdf941ab1cf7043c3c8

**Review by lagoan — CHANGES_REQUESTED** [review]
We just need a CHANGELOG entry and we are set.

**Review by lagoan — APPROVED** [review]
LGTM!
