### PR TITLE
Fix/Re-Enable "Create Plan" RSpec Test

### LINKED ISSUE #797: Address RSpec Tests Specifically Disabled For DMP Assistant
Please complete the following fields as applicable:

**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**
`4.1.1+portage-4.1.0-uat-4` `4.1.1+portage-4.1.0-alpha-3`

#### "Pending" tests after executing `rspec` for DMP Roadmap (`v4.2.0`):
```
Pending: (Failures listed here are expected and do not affect your suite's status)

  1) ResearchOutput instance methods metadata_standards should have tests once implemented
     # Temporarily skipped with xit
     # ./spec/models/research_output_spec.rb:61

  2) ResearchOutput instance methods repositories should have tests once implemented
     # Temporarily skipped with xit
     # ./spec/models/research_output_spec.rb:58

  3) ResearchOutput instance methods resource_types should have tests once implemented
     # Temporarily skipped with xit
     # ./spec/models/research_output_spec.rb:64

  4) ResearchOutput instance methods licenses should have tests once implemented
     # Temporarily skipped with xit
     # ./spec/models/research_output_spec.rb:55

  5) Condition add some examples to (or delete) /home/aaron/Documents/GitHub/roadmap_upstream/spec/models/condition_spec.rb
     # Not yet implemented
     # ./spec/models/condition_spec.rb:6
```
#### "Pending" tests after executing `rspec` for DMP Assistant:
```
  1) Plans User creates a new Plan
     # Temporarily skipped with xit
     # ./spec/features/plans_spec.rb:35

  2) Condition add some examples to (or delete) /home/aaron/Documents/GitHub/roadmap/spec/models/condition_spec.rb
     # Not yet implemented
     # ./spec/models/condition_spec.rb:6

  3) FeatureFlagHelper Pending Test: Feature Flag
     # No reason given
     # ./spec/helpers/feature_flag_helper_spec.rb:7

  4) ResearchOutput instance methods licenses should have tests once implemented
     # Temporarily skipped with xit
     # ./spec/models/research_output_spec.rb:55

  5) ResearchOutput instance methods resource_types should have tests once implemented
     # Temporarily skipped with xit
     # ./spec/models/research_output_spec.rb:64

  6) ResearchOutput instance methods repositories should have tests once implemented
     # Temporarily skipped with xit
     # ./spec/models/research_output_spec.rb:58

  7) ResearchOutput instance methods metadata_standards should have tests once implemented
     # Temporarily skipped with xit
     # ./spec/models/research_output_spec.rb:61

  8) Locales when new locale has no region user changes their locale
     # We are now expecting locales to have region
     # ./spec/features/locales_spec.rb:51
```
#### "Pending" tests exclusive to DMP Assistant:
```
  1) Plans User creates a new Plan
     # Temporarily skipped with xit
     # ./spec/features/plans_spec.rb:35

  3) FeatureFlagHelper Pending Test: Feature Flag
     # No reason given
     # ./spec/helpers/feature_flag_helper_spec.rb:7

  8) Locales when new locale has no region user changes their locale
     # We are now expecting locales to have region
     # ./spec/features/locales_spec.rb:51
```

### PR DESCRIPTION
**Pull request by aaronskiba**
Fixes #797

Changes proposed in this PR:

[Fix "Create a new plan" features test](https://github.com/portagenetwork/roadmap/pull/798/commits/1b082dc1494aa8ed54eee79139fbca19903759b2)
- The "Create Plan" UI and logic For DMP Assistant diverges from that of DMP Roadmap. This commit adapts the tests within `spec/features/plans_spec.rb` to be compatible with DMP Assistant.
- NOTE: I don't believe the `stub_openaire` call is required, so it has been removed for this test.

### CODE REVIEW

File: spec/features/plans_spec.rb [hunk 1]
```diff
@@ -10,7 +10,8 @@
     @org = create(:org)
     @research_org = create(:org, :organisation, :research_institute,
                            name: 'Test Research Org', templates: 1)
-    @funding_org  = create(:org, :funder, name: 'Test Funder Org', templates: 1)
+    Rails.application.config.default_funder_name = 'Test Funder'
```
Comment (aaronskiba) [inline spec/features/plans_spec.rb]: After merging #814, this will have to use `Rails.application.config.default_funder_id`.

File: spec/features/plans_spec.rb [hunk 2]
```diff
@@ -10,47 +10,39 @@
...
-    #               115797 - INNODIA - Translational approaches to disease modifying therapy of ...
-    #             </displayed-value>
-    #             <stored-value>info:eu-repo/grantAgreement/EC/H2020/115797/EU</stored-value>
-    #           </pair>
-    #         </value-pairs>
-    #       </form-value-pairs>
-    #     XML
-    #     )
+  after do
+    Rails.application.config.default_funder_id = @original_default_funder_id
```
Comment (momo3404) [inline spec/features/plans_spec.rb:23]: Just curious on the reason for this `after` call. I'm assuming it's because other tests might manipulate `Rails.application.config.default_funder_id` but just wanted to double check.

Comment (aaronskiba) [reply spec/features/plans_spec.rb:23]: Yes, you're correct. This might be the only using it right now, but maybe still best to do it this way after what we encountered with those other flaky tests that overwrote the config.

Comment (momo3404) [reply spec/features/plans_spec.rb:23]: I see, just wanted to understand why. I agree that it's best to add it as future protection.

**Review by momo3404 — DISMISSED** [review]

**Review by momo3404 — APPROVED** [review]
