### PR TITLE
Clean Up `/contact-us` Page, Fix "Contact us" Footer Link, and Update `terms_of_use_path`

### LINKED ISSUE #961: Contact Us pointing to old domain
In the footer, "contact us" links to portagenetwork.ca/contact-us so it redirects to the Alliance website

Could we also, while fixing this, hide the address and phone number so it's just the contact form? This might streamline our current support queue where some stuff is coming in through other channels.

### PR DESCRIPTION
**Pull request by aaronskiba**
Fixes #961

Changes proposed in this PR:
- Prevent dummy values for "telephone", "address", and "google_maps_link" from being rendered within `/contact-us` page.
- Fix variable name typos within `config.x.organisation.address` to properly correspond with variable names within `app/views/contact_us/contacts/_new_right.html.erb`.
- Override/undo overriding of `contact_us_path`
  - `contact_us_path` now defaults to the following via the `contact_us` gem:
      ```
      3.1.4 :001 > Rails.application.routes.url_helpers.contact_us_path
      => "/contact-us"
      3.1.4 :002 > I18n.locale = :'fr-CA'
      => :"fr-CA"
      3.1.4 :003 > Rails.application.routes.url_helpers.contact_us_path
      => "/contact-us"
      ```
- Replace `def terms_of_use_path` Rails convention `terms_path`.

### CODE REVIEW

File: app/helpers/application_helper.rb [hunk 1]
```diff
@@ -53,26 +53,6 @@ def current_locale_logo
...
-  def terms_of_use_path
-    'https://dmp-pgd.ca/terms' # TEMPORARY FIX
-    # if I18n.locale == :'fr-CA'
-    #   'https://portagenetwork.ca/fr/outils-et-ressources/assistant-pgd/conditions-dutilisation-de-lassistant-pgd/'
-    # else
-    #   # Handling :'en-CA' locale
-    #   'https://assistant.portagenetwork.ca/terms'
-    # end
-  end
-
```
Comment (momo3404) [inline app/helpers/application_helper.rb:75]: Just wondering- how would the translation work here?

**Review by momo3404 — DISMISSED** [review]

File: app/helpers/application_helper.rb (hunk 1 above)
Comment (aaronskiba) [reply app/helpers/application_helper.rb:75]: Good question. The language selector within the app updates `I18n.locale`. So something like `if I18n.locale == :'fr-CA'` can be thought of as "Does the user currently have the language selector set to French?"

If you're curious, I think `app/controllers/session_locales_controller.rb` handles the language selector updates.

Comment (momo3404) [reply app/helpers/application_helper.rb:75]: Makes sense, thanks for clarifying!

**Review by momo3404 — APPROVED** [review]
