### PR TITLE
re-add sandbox seeds file after git history fix

### LINKED ISSUE #167: Date Format Question Forcing Adding Option with Accompanying Text
When adding/editing questions, I am unable to add a "Date" format question, receiving the following Error message: "Unable to create the question. You must have at least one option with accompanying text." - this also appears to be an issue in prod.

@robynnicholson just want to confirm what this issue is expected to be, should be date format question go without option naturally, or it should have the option field available to the user?

Currently, the error is because the option field is not available to the user, but it requires the user to input text when saving.

### LINKED ISSUE #172: Organization type(s) Floatover Text Update: Incorrect Contact & Translation
On the "Organization details" page, the tooltip floatover text requires updating to reflect the correct contact information: support@portagenetwork.ca, not "info@alliancecan.ca". 
Screenshot 2022-04-01 115604

Additionally, the text is not translated on the French interface.
Screenshot 2022-04-01 115546

### PR DESCRIPTION
**Pull request by pengyin-shan**
A new PR includes the seed file for sandbox testing after we adjust git history.

Pre-set credentials are included for user accounts (which may trigger the GitGuardian report), but they are just for test and we can change them later.

Includes sample plans & roles, templates, guidance, questions, answers, organizations and locals, as three admin accounts as super admin, organizational admin and institutional admin (belonging to three main organizations).

Statistics page are using fake statistics (generated in seed) instead of running `rake stat:build`. **We cannot run `rake stat:build` after seeding because the new results will overwrite the fake statistics.** 

The reason to use fake statistics is that on my local machine, the charts won't populate data correctly (without any error message) using the statistics generated by `rake stat:build`. We can update the seed file later after this issue is resolved.

Please feel free to test on your machine and let me know if I miss anything. Thank you!

### CODE REVIEW

File: db/seeds_sandbox.rb [hunk 1]
```diff
@@ -0,0 +1,1038 @@
...
+        themes:  [Theme.all.sample],
+        created_at: 4.years.ago
+      }
+    Guidance.create(guidance)
+    end
+
+  # Three standard templates for default org, funder admin's org and insitutional admin's org
+  # Templates are created 3 years ago
+  # -------------------------------------------------------
+  templates = [
```
Comment (lagoan) [inline db/seeds_sandbox.rb]: We should add at least one of DMP Assistant's default Portage templates. It will be a bit of work but it will be very beneficial to the people testing the application.

You can try following the approach outlined [here](https://medium.com/railstips/create-seed-file-from-data-already-in-database-in-rails-660e5ab92b5).

Let me know if you have any questions.

**Review by lagoan — CHANGES_REQUESTED** [review]
This is a great start!

We should add templates from the current list of default Portage templates. 
It would also be great if we could have the organizations use some logos so users know what they will be changing.

**Comment by pengyin-shan** [comment]
> This is a great start!
> 
> We should add templates from the current list of default Portage templates. It would also be great if we could have the organizations use some logos so users know what they will be changing. 

As a note, the rake task-related files are just for generating the database-export seed files. I separated rake tasks and seed files to force the seed process to run in sequence. running `rake export:build_sandbox_data` will write seed command to seed_1.rb, seed_2.rb and seed_3.rb. seed_0.rb, seed_4.rb and seed_5.rb contain manually edited content.

When we deploy to the sandbox environment, just change the `seed_sandbox.rb` to `seed.rb` and run the seed command. `seed.rb` will read seed_0 to seed_5 and write corresponding data to the sandbox database

File: Dockerfile.production [hunk 2]
```diff
@@ -35,6 +35,7 @@ ENV INSTALL_PATH $INSTALL_PATH
 WORKDIR $INSTALL_PATH
 RUN gem install bundler
 
+COPY /db/ /usr/src/app/db/
```
Comment (lagoan) [inline Dockerfile.production]: We shouldn't need to copy this directory over to the image path, did you run into problems if you did not copy it ?

File: Gemfile [hunk 3]
```diff
@@ -366,4 +366,6 @@ end
 
 group :production, :staging, :sandbox do
   gem 'syslog-logger'
+  # For sandbox testing
+  gem "faker"
```
Comment (lagoan) [inline Gemfile:374]: the faker gem should only be added to `staging` environment not on `production` and `staging` environments

File: db/seeds/seeds_0.rb [hunk 4]
```diff
@@ -0,0 +1,149 @@
+
+require 'faker'
```
Comment (lagoan) [inline db/seeds/seeds_0.rb]: I don't think you need to require the gem here, I believe it is available if you add it to the Gemfile.

File: db/seeds_sandbox.rb [hunk 5]
```diff
@@ -0,0 +1,20 @@
...
+########## This file serves for the sandbox testing after 3.0 release
+# Steps:
+# 1) change default database to production database, then run `rails export:build_sandbox_data` to generate production-related data
+# 2) switch database to the sandbox database
+# 3) run rake db:seed or created alongside the db with db:setup to seed data
+##########
+
+# Forcing load seed file in sequence.rb
+# seeds_1 to seeds_3 are rake-generated. Other seeds file are manually edited
+Dir[File.join(Rails.root, 'db', 'seeds', '*.rb')].sort.each_with_index do |seed, index|
```
Comment (lagoan) [inline db/seeds_sandbox.rb:16]: will `sort` sort them alphabetically ? I don't think we will run into the problem where we have more than 10 seeds but we should check just in case.

File: lib/tasks/export_portage_1.rake [hunk 6]
```diff
@@ -0,0 +1,51 @@
+# To maintain the original hierarchy, all items below needs to keep the original id
+
+require 'faker'
+
+namespace :export do
+  desc "Export org, guidance_group and guidance from 3.0.2 database" 
+  task :export_portage_1 => :environment do
+    excluded_keys = ['created_at','updated_at'] 
+    Org.all.each do |org|
+      if org.id == 8 # super admin's org: Portage network/Alliance in production database
```
Comment (lagoan) [inline lib/tasks/export_portage_1.rake]: What do you think about fetching the first super administrator's org and working directly with it instead of depending on the current state of the production database?

**Review by lagoan — DISMISSED** [review]
LGTM

File: lib/tasks/export_portage.rake [hunk 7]
```diff
@@ -69,6 +73,9 @@ namespace :export_production_data do
             end
             QuestionFormat.all.each do |question_formats| 
                 excluded_keys = ['created_at','updated_at'] 
+                if question_formats.id == 7
+                    question_formats.option_based = FALSE
```
Comment (lagoan) [inline lib/tasks/export_portage.rake:77]: Is this still needed? You are already setting the `option_based` value to `false` on line 106 from db/seeds/seeds_1.rb

Comment (lagoan) [reply lib/tasks/export_portage.rake:77]: @pengyin-shan

Comment (pengyin-shan) [reply lib/tasks/export_portage.rake:77]: @lagoan I left it here because the current production database is still set the `option_based` to TRUE, so in case I need to re-generate the seed files (including seeds_1.rb) again (for example, re-run this task before the sandbox deployment), the value in seeds_1b.rb will be overwritten. I could remove it but need to put a note for this part.

Comment (pengyin-shan) [reply lib/tasks/export_portage.rake:77]: I put a note at #167 for asking Neil to modify the current production database, but I was thinking to do it after the sandbox deployment...probably I can do it now then remove this line?

Comment (lagoan) [reply lib/tasks/export_portage.rake:77]: @pengyin-shan sounds good!

**Review by lagoan — DISMISSED** [review]

**Review by lagoan — APPROVED** [review]
